// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// author © KivancOzbilgic
// developer © KivancOzbilgic
//@version=5
strategy('AlphaTrend-SA', shorttitle='AT-SA', overlay=true, format=format.price, precision=2, default_qty_value = 1000, default_qty_type = strategy.cash, initial_capital = 1000) // timeframe=''
coeff = input.float(1, 'Multiplier', step=0.1)
AP = input(14, 'Common Period')
ATR = ta.sma(ta.tr, AP)
src = input(close)
novolumedata = input(title='Change calculation (no volume data)?', defval=false)
orderSize = input.float(500.0, "Order Size USDT")
useConfirmation = input.bool(true,"Use Confirmation?")
useOrderClose = input.bool(false, "Use close oreder? (for test) ")
qty = orderSize / close
upT = low - ATR * coeff
downT = high + ATR * coeff
AlphaTrend = 0.0
AlphaTrend := (novolumedata ? ta.rsi(src, AP) >= 50 : ta.mfi(hlc3, AP) >= 50) ? upT < nz(AlphaTrend[1]) ? nz(AlphaTrend[1]) : upT : downT > nz(AlphaTrend[1]) ? nz(AlphaTrend[1]) : downT

color1 = AlphaTrend > AlphaTrend[2] ? #00E60F : AlphaTrend < AlphaTrend[2] ? #80000B : AlphaTrend[1] > AlphaTrend[3] ? #00E60F : #80000B
k1 = plot(AlphaTrend, color=color.new(#0022FC, 0), linewidth=3)
k2 = plot(AlphaTrend[2], color=color.new(#FC0400, 0), linewidth=3)

fill(k1, k2, color=color1)

buySignalk = ta.crossover(AlphaTrend, AlphaTrend[2])
sellSignalk = ta.crossunder(AlphaTrend, AlphaTrend[2])


K1 = ta.barssince(buySignalk)
K2 = ta.barssince(sellSignalk)
O1 = ta.barssince(buySignalk[1])
O2 = ta.barssince(sellSignalk[1])

//plotshape(buySignalk and showsignalsk and O1 > K2 ? AlphaTrend[2] * 0.9999 : na, title='BUY', text='BUY', location=location.absolute, style=shape.labelup, size=size.tiny, color=color.new(#0022FC, 0), textcolor=color.new(color.white, 0))
//plotshape(sellSignalk and showsignalsk and O2 > K1 ? AlphaTrend[2] * 1.0001 : na, title='SELL', text='SELL', location=location.absolute, style=shape.labeldown, size=size.tiny, color=color.new(color.maroon, 0), textcolor=color.new(color.white, 0))

if useConfirmation
    // Confirmed
    c_buyCondition = buySignalk[1] and O1[1] > K2
    c_sellCondition = sellSignalk[1] and O2[1] > K1

    c_combinedCondition = c_buyCondition or c_sellCondition

    if c_buyCondition
        if useOrderClose
            strategy.close('sell')
        strategy.order('buy', strategy.long, qty)
    else if c_sellCondition
        if useOrderClose
            strategy.close('buy')
        strategy.order('sell', strategy.short, qty)

else
    // Not Confirmed
    buyCondition = buySignalk and O1 > K2
    sellCondition = sellSignalk and O2 > K1

    if buyCondition
        if useOrderClose
            strategy.close('sell')
        strategy.order('buy', strategy.long, qty)
    else if sellCondition
        if useOrderClose
            strategy.close('buy')
        strategy.order('sell', strategy.short, qty)


