version: "3"
services:

  mysql:
    container_name: x7sfutures_mysql
    image: mariadb:10.6
    volumes:
      - .docker/data/db:/var/lib/mysql
      - .docker/init/database:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: x7sfutures
      MYSQL_USER: x7sfutures
      MYSQL_PASSWORD: x7sfutures
    restart: unless-stopped

  phpmyadmin:
    container_name: x7sfutures_pma
    image: phpmyadmin/phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: x7sfutures_mysql
      PMA_USER: x7sfutures
      PMA_PASSWORD: x7sfutures
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: x7sfutures
      MYSQL_PASSWORD: x7sfutures
    depends_on:
      - mysql

#  node:
#    container_name: x7sfutures_node
#    build: ./
#    ports:
#      - "3388:3388"
#    environment:
#      - PORT=3388
#      - DOCKER=true
#    volumes:
#      - .:/home/wwwroot/x7sfutures
#    depends_on:
#      - mysql
#    extra_hosts:
#      - host.docker.internal:host-gateway

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'x7sfutures_rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

#  dragonfly:
#    image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.11.0
#    ports:
#      - "6380:6379"
#    ulimits:
#      memlock: -1